Pipfile
Pipfile.lock
gunicorn.conf.py
historical_system_profiles/app.py
historical_system_profiles/app_config.py
historical_system_profiles/openapi/api.spec.yaml
historical_system_profiles/views/v0.py
run_app.sh
run_unit_tests.sh
scripts/create-manifest.py
setup.cfg
standalone_flask_server.py

This commit sets up the service and returns /version on v0.

initial commit

---

historical_system_profiles/mock_data/mocks.py
historical_system_profiles/openapi/api.spec.yaml
historical_system_profiles/views/v0.py
wsgi.py

This adds a mock list of profiles to return for a single system uuid.

feature: add mock data for profiles for a uuid

---

historical_system_profiles/app.py
historical_system_profiles/config.py
historical_system_profiles/db_interface.py
historical_system_profiles/views/v0.py

This commit factors out the database code into a new `db_interface.py`
file. This is needed for the upcoming listener changes.

fix: factor DB code out of view

---

historical_system_profiles/config.py
run_app.sh

The 'namespace' variable was not defined. This PR pulls it in.

updates for cloudwatch logging

---

clean_expired_records.py
historical_system_profiles/config.py
historical_system_profiles/db_interface.py
run_app.sh

This deletes records that were created more than
VALID_PROFILE_AGE_DAYS days ago. It pauses for
EXPIRED_CLEANER_SLEEP_MINUTES in between runs.

add DB expired record cleaner

---

historical_system_profiles/db_interface.py

Previously, if the database connection died while message processing
was happening, we would keep attempting to re-use the dead connection
instead of creating a new one. This would occur even after the
database came back up.
We now roll back the ORM transaction if there is an error. This lets
us try with a fresh connection on the next run, so if the DB is back
up we will reconnect.

fix: roll back ORM transaction on exception

---

historical_system_profiles/payload_tracker_interface.py
kafka_listener.py

This commit adds the user account and inventory ID to tracker
messages.  It also changes the date format to what the tracker
expects.

feature: add account and inventory ID to tracker

---

historical_system_profiles/archiver.py
historical_system_profiles/deleter.py
kafka_listener.py

This commit refactors some of the archiver and deleter code to make it
more readable. It does not contain any bugfixes or feature changes.

fix: refactor archiver and deleter code

---

historical_system_profiles/deleter.py

This commit invokes the incrementers for delete operations.

add deleter metrics

---

historical_system_profiles/archiver.py
historical_system_profiles/deleter.py

`platform_metadata` is an optional field. This commit better handles
the case when it's not present.

fix platform_metadata error

---

README.md

readme bump to force build

---

historical_system_profiles/views/v1.py

Add standalone hsp rbac

---

.github/pull_request_template.md
.gitignore
README.md
historical_system_profiles/app.py
historical_system_profiles/config.py
historical_system_profiles/db_interface.py
historical_system_profiles/payload_tracker_interface.py
historical_system_profiles/views/v1.py
kafka_listener.py
sonar-scanner.properties.sample

Merge to stable

---

kafka_listener.py

Adding ability to see if secure kafka connection was created by checking logs.

Add log message indication of secure kafka connection.

---

historical_system_profiles/archiver.py
historical_system_profiles/notification_service_interface.py

Need to add inventory_id to the notification event so we build correct urls in email messages.

[DRFT-334] add inventory id to notification event context

---

historical_system_profiles/archiver.py

Skip if data.value is None

---

historical_system_profiles/archiver.py

[DRFT-343] better check for data.value and its content

---

historical_system_profiles/archiver.py

Push to QA

---

historical_system_profiles/archiver.py

Adds temporary logging of kafka messages in archiver.

---

historical_system_profiles/archiver.py

Updates temp kafka message logging

---

scripts/update-kerlescan.sh

Adds script to help updating kerlescan

---

Dockerfile

Add dockerfile to hsp backend

---

historical_system_profiles/archiver.py
historical_system_profiles/notification_service_interface.py

Added by mistake in place of inventory_id initially; removing.

[DRFT-338] Remove insights-id from notifications

---

build_deploy.sh

Temporarily rename qa tag

---

build_deploy.sh

This reverts commit ecd2924656232a4f1712b46ae527e24414f93e94.

Revert "Temporarily rename qa tag"

---

historical_system_profiles/config.py
historical_system_profiles/notification_service_interface.py
kafka_listener.py

[DRFT-244] Add kafka user/pass to hsp

---

historical_system_profiles/notification_service_interface.py
kafka_listener.py

sasl_user/pass needs to be plain

---

historical_system_profiles/archiver.py
historical_system_profiles/baseline_service_interface.py

Add baseline name to notifications

---

Pipfile.lock
historical_system_profiles-manifest

Updates Pipfile.lock with latest versions

---

clowdapp.yaml

Load the iqe drift plugin when hsp is deployed

---

clowdapp.yaml

[DRFT-735] Get notifications-backend running together with HSP

---

build_deploy.sh

Fix image build after PR is merged into master

---

README.md

Adds psql requirements for development to README

---

historical_system_profiles/deleter.py

Adds debug logging of kafka message received in deleter

---

README.md
clowdapp.yaml
ephemeral_build_image.sh

[DRFT-776] Create ephemeral build_image script

---

clowdapp.yaml

[DRFT-785] Fix HSP clowdapp.yaml dependencies

---

clowdapp.yaml

Clowder fix HB name

---

clowdapp.yaml

Fix DB name in Clowder

---

clowdapp.yaml

[DRFT-796] Check why Notifications email is not working

---

clowdapp.yaml

force build

---

clowdapp.yaml
run_app.sh

Exclude CJI and adapt run_app.sh to run migration

---

run_app.sh

[DRFT-856] - Run apps in both public and metrics ports (8000 and 9000)

---

scripts/update-kerlescan.sh

Updates only kerlescan with update-kerlescan.sh

---

README.md

Change password in README

---

historical_system_profiles/config.py

[DRFT-948] Consume Kafka SSL configs from Clowder

---

clowdapp.yaml

Add SSL check env var to clowdapp pods

---

historical_system_profiles/config.py

Stop using Clowder config for Kafka SSL security protocol

---

historical_system_profiles/config.py

Fix kafka_sasl_mechanism env variable

---

historical_system_profiles/config.py

Change the way we handle sasl username and password

---

clowdapp.yaml
historical_system_profiles/archiver.py
historical_system_profiles/listener_logging.py
kafka_listener.py

Add more logging to HSP

---

historical_system_profiles/notification_service_interface.py
historical_system_profiles/payload_tracker_interface.py
kafka_listener.py

Remove ssl_check_hostname parameter

---

historical_system_profiles/app.py
historical_system_profiles/hsts_response.py
run_app_locally.sh

[DRFT-872] Add HSTS header in all responses

---

historical_system_profiles/archiver.py

[DRFT-992] Added account id to archiver logs

---

check_cleaner_liveness_probe.sh
check_liveness_probe.sh
check_readiness_probe.sh
clean_expired_records.py
clowdapp.yaml
historical_system_profiles/archiver.py
historical_system_profiles/config.py
historical_system_profiles/deleter.py
historical_system_profiles/probes.py

Periodically touch liveness probe file.
Touch readiness probe file once.
Adds scripts checking for probe files and test them if they are old
(ie not touched in a period of time).
Adds parameters and ENV to clowdapp config.
Adds probes definitions to clowdapp config.

[DRFT-1033] Adds liveness and readiness probes to archiver, deleter, cleaner

---

historical_system_profiles/notification_service_interface.py

This reverts commit 3f28a5ed61ad0258dc9022afd42594a63831f5b3.

Revert "Add description and url for events"

---

.pre-commit-config.yaml

Updates pre-commit config

---

migrations/versions/e07ac5a2cd11_adds_org_id.py

[DRFT-1110] org_id db migration - column creation

---

clowdapp.yaml
org-id-populator-job.yaml

- Adds ENV variables needed for translator service to clowdapp.yaml
- Sets up org-id-populator job
- Adds POPULATOR_LOG_FORMAT for hsps-org-id-populator job

[DRFT-1126] org id populator job

---

historical_system_profiles/archiver.py
historical_system_profiles/config.py
historical_system_profiles/db_interface.py
historical_system_profiles/deleter.py
historical_system_profiles/models.py
historical_system_profiles/notification_service_interface.py
historical_system_profiles/openapi/api.spec.yaml
historical_system_profiles/payload_tracker_interface.py
historical_system_profiles/views/v1.py
tests/fixtures.py
tests/test_archiver.py
tests/test_db_interface.py
tests/test_v1_api.py

- Adds org_id to db_interface only
- Updates fixtures with org_id
- Adds org_id to models only
- Adds org_id to payload track only
- Adds org_id to notification service interface only
- Adds org_id to archiver only
- notification service formatting
- Fixtures formatting
- Adds org_id to deleter
- Adds org id to v1
- adds org id to api spec
- formatting of config.py

Implements storing of and querying by org id

---

historical_system_profiles/views/v1.py

Removes ensure_account_number to allow anemic tenants

---

clowdapp.yaml

Pins up tenant-utils image for org-id-populator

---

clowdapp.yaml

[DRFT-1171] Sets batch size and timeout for org-id job

---

historical_system_profiles/db_interface.py

[DRFT-1172]
This ensures that the query returns records that do not have org_id
popupated yet.

Switches priority checks for account_number and org_id in queries

---

historical_system_profiles/db_interface.py

This reverts commit 35821d2cdd76939c3950987bada5e7eee4e3fc23.

Revert "Switches priority checks for account_number and org_id in queries"

---

clowdapp.yaml

Reduce the batch-size of the org-id-populator job

---

run_app.sh

Downgrade stage database migration to revert account field index addition, as this should not be applied on prod and will be reverted.
Note that alembic fails when a migration file is missing.
DRFT-1175

fix(db): downgrade stage account index

---

clowdapp.yaml

Corrects indentation for config of probes

---

historical_system_profiles/config.py
hsp_deploy_ephemeral_env.sh
kafka_listener.py

Changes the loading of kafka cacert from clowder

---

run_app.sh
run_app_locally.sh

Sets limit-request-field_size for gunicorn to 16k

---

.github/workflows/checkimage.yaml

feature(image): automatic pull request when new base image or rpms are present

---

clowdapp.yaml

----
- Updating references from the old 3scale dev deployment `apicast.3scale-dev.svc.cluster.local` to the new 3scale dev deployment `gateway.3scale-dev.svc.cluster.local`
- The reason for this change is the Infrastructure Team has stood up a new 3scale (Gateway) Deployment to support service serving certificates. Currently, both the old and new deployments are running in parallel so we can aid workstreams in the change over.   

Update References to 3Scale Dev Deployment

---

clowdapp.yaml

This adds apiPath historical-system-profiles to the clowd app. This will help get RHCLOUD-20273 closed.

Add apiPath to clowd app public web service

---

run_app.sh

Adds shebang to run_app.sh script

---

Dockerfile

Uses pipenv sync in Dockerfile

---

check_cleaner_liveness_probe.sh
check_liveness_probe.sh
check_readiness_probe.sh
clowdapp.yaml
historical_system_profiles/config.py

Moves liveness and readiness probes files to /tmp

---

.travis.yml
Dockerfile

Pins poetry in CI and Dockerfile

---

hsp_deploy_ephemeral_env.sh

Corrects multiline command in deploy script

---

poetry.lock
pyproject.toml

Bumps kerlescan to include fedramp tls config

---

hsp_deploy_ephemeral_env.sh

Keeps resources for Drift in PR check

---

.travis.yml
Dockerfile

Updates poetry to 1.4

---

scripts/update-kerlescan.sh

Updates lockfile when updating kerlescan

---

build_deploy.sh

Adding branch tagging into for the "security-compliance" branch

Add branch tagging updates

---

build_deploy.sh

Fix build deploy formatting error

Fix build deploy formatting error

---

build_deploy.sh

Update build-deploy with security-compliance branch changes.

Update build-deploy with security-compliance branch changes

---

.github/workflows/checkimage.yaml
.github/workflows/ci-dev-tests.yml
.github/workflows/update_manifest_dependabot_pr.yml

- Adds name and uses token in check image GH action
- Adds name and condition to not run Dependabot's actions
- Adds GH action to update manifest on Depedabot's PRs
DRFT-1345

manifest updates for dependabot prs

---

hsp_deploy_ephemeral_env.sh

Removes pool selection from bonfire deploy command

---

poetry.lock
pyproject.toml

upgrade kerlescan

---

poetry.lock
pyproject.toml

bump kerlescan

---

historical_system_profiles/app.py
poetry.lock
pyproject.toml

Registers gunicorn access and error logs to cloudwatch handler.
RHINENG-1050

feat(app): log guinicorn to cloudwatch

---

clowdapp.yaml

To optimize resources easily, these values should be made configurable using parameters.
I copied the current settings into the default values in the params so there's no need to change any params in app-interface.
JIRA: https://issues.redhat.com/browse/RHINENG-2174

feat: make resources configurable by deployment

---

Dockerfile

chore: modify Dockerfile to benefit more from layer caching

---

historical_system_profiles/archiver.py

feat: builds identity header from host content if missing in metadata

---

historical_system_profiles/archiver.py
tests/test_archiver.py

feat: decouples updating baselines from drift event check

---

clowdapp.yaml

Not needed anymore
RHINENG-2178

chore: removes org-id-populator job

---

historical_system_profiles/archiver.py
poetry.lock
pyproject.toml

feat: Filters out CentOS systems

---

historical_system_profiles/views/v1.py
tests/fixtures.py
tests/test_v1_api.py

https://issues.redhat.com/browse/ESSNTL-5251
https://github.com/RedHatInsights/historical-system-profiles-backend/pull/388

feat: filter HSPs by access to inventory groups

---

historical_system_profiles/config.py

feat: Uses KafkaServers from app_common_python for kafka config

---

pyproject.toml

Updating kerlescan to allow `service_account`

feat(RHINENG-6114) Allow ServiceAccount

---

poetry.lock
pyproject.toml

chore: removes Bearer from Unleash auth header by bumping kerlescan

---

ephemeral_unit_test.sh

postgresql-rds "-1" images are being deprecated; moving to postgresql-rds:cyndi-13 instead

refactor(dev): update postgresql-rds image tag

---

clean_expired_records.py
historical_system_profiles/app.py
historical_system_profiles/archiver.py
historical_system_profiles/deleter.py
historical_system_profiles/listener_logging.py
historical_system_profiles/notification_service_interface.py
kafka_listener.py
poetry.lock
pyproject.toml

Logging changes I've made so far are to reflect the following levels:
Debug - `Detailed information, typically only of interest to a developer trying to diagnose a problem.`
Info - `Confirmation that things are working as expected.`
Warning - `An indication that something unexpected happened, or that a problem might occur in the near future (e.g. ‘disk space low’). The software is still working as expected.`
Error - `Due to a more serious problem, the software has not been able to perform some function.`
The custom log level `Audit` has been touched one time, where I think the `info` log level is more adequate. Regarding the rest of audit logs, I'm waiting for App SRE to decide what to do.

feat(RHINENG-7984): implement logging best pracices

---

build_deploy.sh

fix: Don't push into commit hash tag from "sc" branch
