- Pipfile
- Pipfile.lock
- historical_system_profiles/app.py
- historical_system_profiles/mgmt_views/v0.py
- historical_system_profiles/openapi/mgmt_api.spec.yaml
- wsgi.py
This commit exposes `/mgmt/v0/status` and `/mgmt/v0/metrics`.
The status page simply returns a static "this is running" json, and
the metrics page is currently blank. As metrics are regsitered, it
will fill in.
> feature: add management plane

- historical_system_profiles/openapi/api.spec.yaml
- historical_system_profiles/views/v0.py
Previously, if an API request had multiple historical system profiles,
we would only return the first profile found. We would also return a 500
error if there were no profiles found for a given inventory ID.
This commit handles these cases. We now return an empty array if no
profiles are found for an inventory ID. We also return all requested
profiles.
> fix: handle requests for multiple HSPs

- Pipfile
- Pipfile.lock
- historical_system_profiles/openapi/api.spec.yaml
- historical_system_profiles/views/v0.py
We were previously using an older version of connexion.
This version upgrades to 2.6 and removes a workaround in a POST
method.
> fix: use connexion 2.6

- historical_system_profiles/openapi/api.spec.yaml
We previously had a lot of bare "object" references as part of
prototyping. These have been removed and replaced with better
definitions.
> fix: remove bare object references from api spec

- historical_system_profiles/openapi/api.spec.yaml
- historical_system_profiles/views/v0.py
We previously would send `{"data": []}` if no profiles were found for a
given ID, but would send a more complex data structure if profiles were
found. This ended up requiring two cases to handle the various returned
values.
We now return `{"data": {"profiles": [<profile1>, <profile2>, ...]}}`
every time. If no data is returned, we simply don't populate the
"profiles" list.
> fix: change format of returned profiles for inv id

- historical_system_profiles/models.py
- historical_system_profiles/openapi/api.spec.yaml
- historical_system_profiles/views/v0.py
Previously, we displayed the "created" date of the historical record.
This made little sense for end users since they are not interested in
when a record was written to our DB.
Instead, we display "captured_date" which is when the data was
captured on the host system. If the captured date is not found, we
fall back to using the created date for that field.
> feature: use captured_date instead of created_on

- historical_system_profiles/metrics.py
- historical_system_profiles/views/v0.py
- tests/fixtures.py
- tests/test_v0_api.py
Previously, we would send the user the display_name that was used when
the profile was recorded. Instead, we now fetch the current display_name
and use that.
There will be a follow-up PR to not record the display_name in the
first place, since it's now a dynamically created field.
> feature: fetch the most current name for HSPs

- historical_system_profiles/models.py
- historical_system_profiles/views/v0.py
Older system profiles did not have a `captured_date`, so we would
instead return the `created_on` timestamp from the DB. However, we
were returning this as a datetime and not as a string. This resulted
in issues since sometimes `captured_date` would be a datetime, and
sometimes it would be a string.
This commit moves the time conversion code into the model so it's
consistent. It also simplifies the `captured_date` method.
> fix bug when parsing older system profiles

- historical_system_profiles/views/v0.py
This commit adds a sort when returning profiles for a system.
> fix: sort list of profiles by captured_date

- kafka_listener.py
System profiles do not contain canonical facts like FQDN. This commit
adds the FQDN to the HSP record so it gets picked up during
comparisons.
> fix: add fqdn to HSPs

- historical_system_profiles/app.py
- historical_system_profiles/config.py
- historical_system_profiles/db_interface.py
Previously, our transaction wrapper was invoking the correct method,
but was not returning the return value.
This commit adds a return so the value goes through. This is useful
when you want to know the number of deleted records.
> fix: return the return value through wrapper

- historical_system_profiles/app.py
We previously were using optimistic DB reconnection handling. This
meant that DB connections were assumed to be good, and were only
thrown out after a user got a 500.
Instead, use pessimistic reconnection handling. We now do a "select 1"
on each connection before using it. This lets us do things like
restart the database without raising any 500s to the user.
This commit also gets rid of some deprecated options and moves them to
the DB options dict.
> fix: additional fixups to db conn handling

- historical_system_profiles/config.py
- historical_system_profiles/payload_tracker_interface.py
- kafka_listener.py
This commit adds payload tracker support. When the archiver or deleter
receives a message, it will emit a status update to the tracker queue.
It will then emit another message upon successfully saving the HSP, or
if an error occurs, it will emit an error message as well.
> feature: emit messages to payload tracker

- historical_system_profiles/payload_tracker_interface.py
- kafka_listener.py
Per payload tracker team, use request_id in the message.
> fix: rename payload_id to request_id

- historical_system_profiles/archiver.py
We were previously counting all messages that came in and success
messages, but were not counting error messages.
This commit updates the error handling code to increase the counter.
> update counter on archiver errors

- historical_system_profiles/models.py
- run_unit_tests.sh
- tests/test_db_interface.py
- tests/test_v1_api.py
- tests/utils.py
Previously, we were relying on the ORM to set the `created_on`
timestamp if one was not provided via `captured_on`. This happens
during object save, but we needed it earlier than that.
This commit sets `created_on` early in the `__init__` so it can be
referenced later.
> set `created_on` when object is instantiated

- clean_expired_records.py
- historical_system_profiles/listener_metrics.py
This commit exposes metrics on port 5000 for the expired record
cleaner.  It also tracks the number of expired records that were
removed in each run.
> expose record cleaner metrics

- historical_system_profiles/listener_logging.py
It was previously difficult to determine if cloudwatch was enabled for
the archiver, deleter, and expired record remover. This adds a couple
of lines of logging to print the cloudwatch status.
> add messages around cloudwatch enablement

- historical_system_profiles/listener_logging.py
We should not be creating log groups, per platform team.
> disable log group creation

- .s2i/bin/assemble
- .s2i/bin/init-wrapper
- .s2i/bin/run
- .s2i/bin/usage
Upstream s2i does not allow setting the pipenv version. This commit
pins us to 2018.11.24, which is the last known working version.
This should be a temporary thing until upstream pipenv is updated.
> override pipenv version in s2i

- historical_system_profiles/config.py
- kafka_listener.py
Previously, we used the kafka poll defaults for the number of records
to pull (500), and how long to wait to process said records (5 min).
This seems to work fine for archive processing but does not work for
deletes. Deleting 500 inventory IDs can take longer than 5 minutes in
some cases. When this happens, our kafka client times out and puts the
delete messages back on the queue for reprocessing. This can result in
a pile-up of messages since we are unsuccessfully reprocessing the
same messages over and over.
This commit exposes two options: `KAFKA_MAX_POLL_INTERVAL_MS` (default
5 min) and `KAFKA_MAX_POLL_RECORDS` (default 500). We also now log the
values for these at startup.
> allow kafka poll tuning

- historical_system_profiles/archiver.py
- historical_system_profiles/db_interface.py
- historical_system_profiles/listener_metrics.py
If a reporter updates an inventory record, it will fire an "updated
record" message on the egress topic. However, not all of these updates
actually update the system profile. This results in duplicate system
profiles in the historical DB.
This change to the archiver checks to ensure a record does not already
exist before saving it to the DB.
We could do this more elegantly via a DB uniqueness constraint;
however this way does not require a data migration to clean old
records. We may eventually want to add a constraint once the data is
unique.
Note that this does not do the select and insert in the same
transaction.  I don't anticipate issues arising from this since the
"fail" case (which should be rare) is that we insert two records which
is the current behavior.  Adding a constraint …
> do not save multiple profiles with the same date

- historical_system_profiles/archiver.py
- historical_system_profiles/config.py
- historical_system_profiles/listener_logging.py
We did not log the HSP ID or captured date previously. Additionally, we
were calling cloudwatch incorrectly by using the project name as the
stream name, and some logs were being dropped. Each pod's stream needs a
unique name.
> logging fixups for archiver

- historical_system_profiles/archiver.py
- kafka_listener.py
- tests/fixtures.py
- tests/test_archiver.py
We now use the same inventory  topic for both delete and archive
messages. Since we are now pulling both messages off the same topic,
we added an additional check on archive messages to ensure we are
processing messages of the correct type before proceeding.
> use new inventory topic

- historical_system_profiles/config.py
- historical_system_profiles/payload_tracker_interface.py
- kafka_listener.py
This adds ENABLE_KAFKA_SSL and KAFKA_SSL_CERT env vars and if ENABLE_KAFKA_SSL is set to True, uses the specified cert to do TLS on kafka connection.
> DRFT-60 add secure kafka communication

- historical_system_profiles/archiver.py
- historical_system_profiles/config.py
- historical_system_profiles/notification_service_interface.py
- tests/test_archiver.py
This is the start of KafkaProducer for sending baseline drift notifications to notifications service.
Optional to define the following env vars (default values are the current, correct values):
NOTIFICATION_SERVICE_TOPIC
NOTIFICATION_BUNDLE
NOTIFICATION_APP
> [DRFT-253] Add notification service interface

- run_app.sh
Pass the `--log-level` flag to gunicorn when `$SERVICE_MODE == "REST_API"`. This will improve the ability of ops to debug the app.
> Accept LOG_LEVEL env var

- clowdapp.yaml
`flask db upgrade` will wait for up to two minutes to establish a connection. If the liveness or readiness probe kills the pod before this timeout expires and prints an error, then ops will lack information about what went wrong.
> Wait two mins before starting probes

- clowdapp.yaml
We need to increase memory limits to have working apps
in ephemeral environment which is used by pr checks.
Current memory limits in ephemeral are causing OOM kills of the workers.
Solution is to not remove apps resources in bonfire deploy command.
See https://github.com/RedHatInsights/historical-system-profiles-backend/pull/293
and https://github.com/RedHatInsights/system-baseline-backend/pull/316
Unfortunatelly these PRs means that hsps' non API services
does not comply with the MaxLimitRequestRatio in ephemeral env.
This will solve that :-)
> Increased memory limits for requests

- historical_system_profiles/archiver.py
- historical_system_profiles/db_interface.py
- historical_system_profiles/models.py
- tests/fixtures.py
- tests/test_archiver.py
- Uses variables instead repeated hash access for readability
- Stores group information to hsps as it comes from Kafka
> [ESSNTL-5247] Store Inventory Group info with new HSP entry from Kafka message
